volumes:
  postgres:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.123.234.0/24

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
