version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  rabbitmq:
    image: ghcr.io/rkalkani/rabbitmq-docker:v3.11.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: '1811labs'
      RABBITMQ_DEFAULT_PASS: '1811labs'
      RABBITMQ_DEFAULT_VHOST: '/'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  s3:
    image: bitnami/minio:latest
    volumes:
      - s3:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_DEFAULT_BUCKETS=cdn.1811labs.com

volumes:
  postgres-data:
  rabbitmq:
  s3:
