name: Deploy backend development 2 env

on:
  push:
    branches: ['preview/*']
  workflow_dispatch:

env:
  REMOTE_HOST: deploy@167.99.30.150
  STACK: nest-boilerplate-dev2
  APP_BACKEND_HOST: dev2-api.1811labs.com
  DOCKER_BUILDKIT: 1
  # DOCKER_REGISTRY: registry.digitalocean.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TESTNET_SSH_KEY }}
          known_hosts: ${{ secrets.TESTNET_KNOWN_HOSTS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      # - name: Login to Docker registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.DOCKER_REGISTRY }}
      #     username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      #     password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Deploy backend
        run: |
          export IMAGE_TAG=pre-$(git describe --tags --always)
          task deploy
